/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View.GUI;

import javax.swing.JTextField;

/**
 *
 * @author Utente
 */
public class LandCard extends javax.swing.JFrame {

    /**
     * Creates new form LandCard
     */
    public LandCard() {
        initComponents();
    }

    public JTextField getFourHouse() {
        return fourHouse;
    }

    public void setFourHouse(int fourHouse) {
        this.fourHouse.setText(Integer.toString(fourHouse));
    }

    public JTextField getHomePrice() {
        return homePrice;
    }

    public void setHomePrice(int homePrice) {
        this.homePrice.setText(Integer.toString(homePrice));
    }

    public JTextField getHotel() {
        return hotel;
    }

    public void setHotel(int hotel) {
        this.hotel.setText(Integer.toString(hotel));
    }

    public JTextField getZeroPrice() {
        return zeroHome;
    }

    public void setZeroPrice(int price) {
        this.zeroHome.setText(Integer.toString(price));
    }

    public JTextField getMortgageValue() {
        return mortgageValue;
    }

    public void setMortgageValue(int mortgageValue) {
        this.mortgageValue.setText(Integer.toString(mortgageValue));
    }

    public JTextField getNameLand() {
        return nameLand;
    }

    public void setNameLand(String nameLand) {
        this.nameLand.setText(nameLand);
    }

    public JTextField getOneHouse() {
        return oneHouse;
    }

    public void setOneHouse(int oneHouse) {
        this.oneHouse.setText(Integer.toString(oneHouse));
    }

    public JTextField getThreeHouse() {
        return threeHouse;
    }

    public void setThreeHouse(int threeHouse) {
        this.threeHouse.setText(Integer.toString(threeHouse));
    }

    public JTextField getTwoHouse() {
        return twoHouse;
    }

    public void setTwoHouse(int twoHouse) {
        this.twoHouse.setText(Integer.toString(twoHouse));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        propertyPanel = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        nameLand = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        threeHouse = new javax.swing.JTextField();
        twoHouse = new javax.swing.JTextField();
        oneHouse = new javax.swing.JTextField();
        hotel = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        fourHouse = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        homePrice = new javax.swing.JTextField();
        zeroHome = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        mortgageValue = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();

        propertyPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        propertyPanel.setToolTipText("");

        jTextField2.setFont(new java.awt.Font("Cambria Math", 3, 12)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 3, 1, new java.awt.Color(0, 0, 0)));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout propertyPanelLayout = new javax.swing.GroupLayout(propertyPanel);
        propertyPanel.setLayout(propertyPanelLayout);
        propertyPanelLayout.setHorizontalGroup(
                propertyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE));
        propertyPanelLayout.setVerticalGroup(
                propertyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(propertyPanelLayout.createSequentialGroup()
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 41,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(247, Short.MAX_VALUE)));

        jLabel9.setText("jLabel9");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nameLand.setEditable(false);
        nameLand.setFont(new java.awt.Font("Cambria Math", 1, 10)); // NOI18N
        nameLand.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nameLand.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(nameLand, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 41));

        jLabel1.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/GUI/image/home-icon-silhouette.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 55, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/GUI/image/home-icon-silhouette.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 89, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/GUI/image/home-icon-silhouette.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/GUI/image/home-icon-silhouette.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 25, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/GUI/image/hotel (1).png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/GUI/image/home-icon-silhouette.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 89, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/GUI/image/home-icon-silhouette.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/GUI/image/home-icon-silhouette.png"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 26, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/GUI/image/home-icon-silhouette.png"))); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 23, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/GUI/image/home-icon-silhouette.png"))); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 32, -1));

        threeHouse.setEditable(false);
        threeHouse.setFont(new java.awt.Font("Cambria Math", 0, 10)); // NOI18N
        threeHouse.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(threeHouse, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 60, 16));

        twoHouse.setEditable(false);
        twoHouse.setFont(new java.awt.Font("Cambria Math", 0, 10)); // NOI18N
        twoHouse.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(twoHouse, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 60, 16));

        oneHouse.setEditable(false);
        oneHouse.setFont(new java.awt.Font("Cambria Math", 0, 10)); // NOI18N
        oneHouse.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(oneHouse, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 60, 16));

        hotel.setEditable(false);
        hotel.setFont(new java.awt.Font("Cambria Math", 0, 10)); // NOI18N
        hotel.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(hotel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 60, 16));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/GUI/image/home-icon-silhouette.png"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        fourHouse.setEditable(false);
        fourHouse.setFont(new java.awt.Font("Cambria Math", 0, 10)); // NOI18N
        fourHouse.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(fourHouse, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 60, 16));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/GUI/image/euro.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 20, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/GUI/image/euro.png"))); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/GUI/image/euro.png"))); // NOI18N
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/GUI/image/euro.png"))); // NOI18N
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/GUI/image/euro.png"))); // NOI18N
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 30, 50));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/GUI/image/euro.png"))); // NOI18N
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/GUI/image/euro.png"))); // NOI18N
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 20, 40));

        homePrice.setEditable(false);
        homePrice.setFont(new java.awt.Font("Cambria Math", 0, 10)); // NOI18N
        homePrice.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(homePrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 241, 60, 20));

        zeroHome.setEditable(false);
        zeroHome.setFont(new java.awt.Font("Cambria Math", 0, 10)); // NOI18N
        zeroHome.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        zeroHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroHomeActionPerformed(evt);
            }
        });
        getContentPane().add(zeroHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 261, 60, 20));

        jLabel6.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        jLabel6.setText("Home price");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 60, -1));

        jLabel7.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        jLabel7.setText("Income");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 60, -1));

        jLabel22.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        jLabel22.setText("Mortgage value");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 80, -1));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/GUI/image/euro.png"))); // NOI18N
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));

        mortgageValue.setEditable(false);
        mortgageValue.setFont(new java.awt.Font("Cambria Math", 0, 10)); // NOI18N
        mortgageValue.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(mortgageValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 60, 20));

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setOpaque(true);
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 220, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextField2ActionPerformed

    private void zeroHomeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_zeroHomeActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_zeroHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LandCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LandCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LandCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LandCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LandCard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fourHouse;
    private javax.swing.JTextField homePrice;
    private javax.swing.JTextField hotel;
    private javax.swing.JTextField zeroHome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField mortgageValue;
    private javax.swing.JTextField nameLand;
    private javax.swing.JTextField oneHouse;
    private javax.swing.JPanel propertyPanel;
    private javax.swing.JTextField threeHouse;
    private javax.swing.JTextField twoHouse;
    // End of variables declaration//GEN-END:variables
}
