/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View.GUI;

/**
 *
 * @author Utente
 */
public class PropertyAction extends javax.swing.JFrame {

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JButton doActButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable playerPropertyTable;
    // End of variables declaration//GEN-END:variables

    /**
     * Creates new form PropertyAction
     */
    public PropertyAction() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        closeButton = new javax.swing.JButton();
        doActButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        playerPropertyTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setAlwaysOnTop(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/GUI/image/close.png"))); // NOI18N
        closeButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED,
                new java.awt.Color(204, 204, 204), new java.awt.Color(0, 0, 0), null, null));
        closeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        jPanel1.add(closeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 20, 20));

        doActButton.setBackground(new java.awt.Color(255, 153, 0));
        doActButton.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        doActButton.setText("DO ACT");
        doActButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED,
                new java.awt.Color(204, 204, 204), new java.awt.Color(0, 0, 0), null, null));
        doActButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        doActButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doActButtonActionPerformed(evt);
            }
        });
        jPanel1.add(doActButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 80, 30));

        playerPropertyTable.setAutoCreateRowSorter(true);
        playerPropertyTable.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        playerPropertyTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {

                },
                new String[] {
                        "Property"
                }) {
            @SuppressWarnings("rawtypes")
            Class[] types = new Class[] {
                    java.lang.String.class
            };

            @SuppressWarnings("rawtypes")
            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }
        });
        playerPropertyTable.setDropMode(javax.swing.DropMode.INSERT_ROWS);
        jScrollPane1.setViewportView(playerPropertyTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 220, 300));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 340));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // getter
    public javax.swing.JButton getDoActButton() {
        return doActButton;
    }

    public javax.swing.JTable getPlayerPropertyTable() {
        return playerPropertyTable;
    }

    private void doActButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_doActButtonActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_doActButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_closeButtonActionPerformed
        this.dispose();
    }// GEN-LAST:event_closeButtonActionPerformed

}
