/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View.GUI;

import javax.swing.JTextField;

/**
 *
 * @author Utente
 */
public class SocietyCard extends javax.swing.JFrame {

    /**
     * Creates new form SocietyCard
     */
    public SocietyCard() {
        initComponents();
    }

    public JTextField getAnniuties() {
        return anniuties;
    }

    public void setAnniuties(JTextField anniuties) {
        this.anniuties = anniuties;
    }

    public JTextField getMortgageValue() {
        return mortgageValue;
    }

    public void setMortgageValue(JTextField mortgageValue) {
        this.mortgageValue = mortgageValue;
    }

    public JTextField getNameSociety() {
        return nameSociety;
    }

    public void setNameSociety(JTextField nameSociety) {
        this.nameSociety = nameSociety;
    }

    public JTextField getWithDoubleService() {
        return withDoubleService;
    }

    public void setWithDoubleService(JTextField withDoubleService) {
        this.withDoubleService = withDoubleService;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameSociety = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        anniuties = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        withDoubleService = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        mortgageValue = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nameSociety.setEditable(false);
        nameSociety.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        nameSociety.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nameSociety.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(nameSociety, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 41));

        jLabel1.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        jLabel1.setText("Annuities");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 70, 20));

        anniuties.setEditable(false);
        anniuties.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        anniuties.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(anniuties, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 59, -1, -1));

        jLabel2.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        jLabel2.setText("With double service:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 130, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/GUI/image/euro.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/GUI/image/euro.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, 20));

        withDoubleService.setEditable(false);
        withDoubleService.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        withDoubleService.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(withDoubleService, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        jLabel5.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        jLabel5.setText("Mortgage value:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 110, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/GUI/image/euro.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        mortgageValue.setEditable(false);
        mortgageValue.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        mortgageValue.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(mortgageValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/GUI/image/light-bulb (1).png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, 50));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/GUI/image/fontana.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, -1, 50));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setOpaque(true);
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 220, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SocietyCard.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SocietyCard.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SocietyCard.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SocietyCard.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SocietyCard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField anniuties;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField mortgageValue;
    private javax.swing.JTextField nameSociety;
    private javax.swing.JTextField withDoubleService;
    // End of variables declaration//GEN-END:variables
}
