/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View.GUI;

import javax.swing.JTextField;

/**
 *
 * @author Utente
 */
public class StationCard extends javax.swing.JFrame {

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fourStation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField price;
    private javax.swing.JTextField mortgageValue;
    private javax.swing.JTextField nameStation;
    private javax.swing.JTextField oneStation;
    private javax.swing.JTextField threeStation;
    private javax.swing.JTextField twoStation;
    // End of variables declaration//GEN-END:variables

    /**
     * Creates new form StationCard
     */
    public StationCard() {
        initComponents();
    }

    public JTextField getFourStation() {
        return fourStation;
    }

    public void setFourStation(int fourStation) {
        this.fourStation.setText(Integer.toString(fourStation));
    }

    public JTextField getMortgageValue() {
        return mortgageValue;
    }

    public void setMortgageValue(int mortgageValue) {
        this.mortgageValue.setText(Integer.toString(mortgageValue));
    }

    public JTextField getNameStation() {
        return nameStation;
    }

    public void setNameStation(String nameStation) {
        this.nameStation.setText(nameStation);
    }

    public JTextField getOneStation() {
        return oneStation;
    }

    public void setOneStation(int oneStation) {
        this.oneStation.setText(Integer.toString(oneStation));
    }

    public JTextField getThreeStation() {
        return threeStation;
    }

    public void setThreeStation(int threeStation) {
        this.threeStation.setText(Integer.toString(threeStation));
    }

    public JTextField getTwoStation() {
        return twoStation;
    }

    public void setTwoStation(int twoStation) {
        this.twoStation.setText(Integer.toString(twoStation));
    }

    public JTextField getPrice() {
        return price;
    }

    public void setPrice(int price) {
        this.price.setText(Integer.toString(price));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameStation = new javax.swing.JTextField();
        oneStation = new javax.swing.JTextField();
        twoStation = new javax.swing.JTextField();
        threeStation = new javax.swing.JTextField();
        fourStation = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        mortgageValue = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(220, 290));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nameStation.setEditable(false);
        nameStation.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        nameStation.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nameStation.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 3, 1, new java.awt.Color(0, 0, 0)));
        nameStation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameStationActionPerformed(evt);
            }
        });
        getContentPane().add(nameStation, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 40));

        oneStation.setEditable(false);
        oneStation.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        oneStation.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        oneStation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneStationActionPerformed(evt);
            }
        });
        getContentPane().add(oneStation, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 59, -1, -1));

        twoStation.setEditable(false);
        twoStation.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        twoStation.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(twoStation, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 93, -1, -1));

        threeStation.setEditable(false);
        threeStation.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        threeStation.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(threeStation, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 127, -1, -1));

        fourStation.setEditable(false);
        fourStation.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        fourStation.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(fourStation, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 161, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/GUI/image/train.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/GUI/image/train.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 20, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/GUI/image/train.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, 20));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/GUI/image/train.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 60, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/GUI/image/train.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/GUI/image/train.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 50, 20));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/GUI/image/train.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 30, 20));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/GUI/image/train.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 30, 40));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/GUI/image/train.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 30, 20));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/GUI/image/train.png"))); // NOI18N
        jLabel10.setToolTipText("");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, 20));

        jLabel11.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        jLabel11.setText("Station's price:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        price.setEditable(false);
        price.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        price.setOpaque(true);
        getContentPane().add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 40, -1));

        jLabel12.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        jLabel12.setText("Mortgage value");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 90, 20));

        mortgageValue.setEditable(false);
        mortgageValue.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        mortgageValue.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(mortgageValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, -1, 20));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/GUI/image/euro.png"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/GUI/image/euro.png"))); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/GUI/image/euro.png"))); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/GUI/image/euro.png"))); // NOI18N
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 20, 30));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/GUI/image/euro.png"))); // NOI18N
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, -1, -1));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/GUI/image/euro.png"))); // NOI18N
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 30, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameStationActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_nameStationActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_nameStationActionPerformed

    private void oneStationActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_oneStationActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_oneStationActionPerformed

}
